### ISSUE TITLE
Queue is only started on call to push

### ISSUE THREAD

**Issue by chrisbaron** [atuttle/corq#5]
When a new instance is restored from persistence using loadVia the queue does not drain until the first call to push.

**Comment by chrisbaron** [comment]
i have a fix.  will create a PR.  do you want it against master or develop?  should I bump the version number in the PR, too?

**Comment by atuttle** [comment]
:+1: thanks! Master is fine and no need to bump the version, I'll take care of that when I publish it.

**Comment by atuttle** [comment]
Resolved by #6
